### ISSUE TITLE
dependency issues RHEL 7.4

### ISSUE THREAD

**Issue by pgera** [negativo17/libwebp7#2]
Error: Package: webkitgtk3-2.4.11-2.el7.x86_64 (rhel-x86_64-server-7)
           Requires: libwebp.so.4()(64bit)
           Available: libwebp-0.3.0-3.el7.x86_64 (rhel-x86_64-server-7)
               libwebp.so.4()(64bit)
           Available: libwebp-0.3.0-7.el7.x86_64 (rhel-x86_64-server-7)
               libwebp.so.4()(64bit)
           Installed: libwebp-0.5.1-2.el7.x86_64 (@epel-multimedia)
              ~libwebp.so.6()(64bit)
Error: Package: gvfs-1.30.4-3.el7.x86_64 (rhel-x86_64-server-7)
           Requires: libbluray.so.1()(64bit)
           Available: libbluray-0.2.3-5.el7.x86_64 (rhel-x86_64-server-7)
               libbluray.so.1()(64bit)
           Installed: libbluray-1.0.1-1.el7.x86_64 (@epel-multimedia)
              ~libbluray.so.2()(64bit)
           Available: libbluray-1.0.0-1.el7.i686 (epel-multimedia)
               Not found
Error: Package: webkitgtk4-2.14.7-2.el7.x86_64 (rhel-x86_64-server-7)
           Requires: libwebp.so.4()(64bit)
           Available: libwebp-0.3.0-3.el7.x86_64 (rhel-x86_64-server-7)
               libwebp.so.4()(64bit)
           Available: libwebp-0.3.0-7.el7.x86_64 (rhel-x86_64-server-7)
               libwebp.so.4()(64bit)
           Installed: libwebp-0.5.1-2.el7.x86_64 (@epel-multimedia)
              ~libwebp.so.6()(64bit)
Error: Package: webkitgtk4-plugin-process-gtk2-2.14.7-2.el7.x86_64 (rhel-x86_64-server-7)
           Requires: libwebp.so.4()(64bit)
           Available: libwebp-0.3.0-3.el7.x86_64 (rhel-x86_64-server-7)
               libwebp.so.4()(64bit)
           Available: libwebp-0.3.0-7.el7.x86_64 (rhel-x86_64-server-7)
               libwebp.so.4()(64bit)
           Installed: libwebp-0.5.1-2.el7.x86_64 (@epel-multimedia)
              ~libwebp.so.6()(64bit)
 You could try using --skip-broken to work around the problem

**Comment by scaronni** [comment]
Hello, CentOS has not been updated to 7.4 yet, I'm rebuilding webkitgtk4 from the RHEL channels. If I push that, CentOS updates will break.

I will make some changes to the repository so most of those rebuilds will not be necessary.

**Comment by pgera** [comment]
This has actually exposed some other bug in yum. Even with skip-broken, yum gets stuck in an infinite loop.

**Comment by scaronni** [comment]
From my testing even distro-sync is not able to take into account obsoletes/provides "backwards". So if something obsoletes something else, when distro-syncing, the package that obsoletes is still taken into account for the dependency solving.

**Comment by pgera** [comment]
Is there any way to downgrade or remove all the epel-multimedia packages ?

**Comment by pgera** [comment]
For now, I've removed all the repo packages with nodeps, and updated the rest of the system.

**Comment by pgera** [comment]
Seeing this slightly different error on a different system which has ffmpeg installed. It passes the dependency checks, but fails with "Transaction check error:
  file /usr/lib64/libwebpdemux.so.2 from install of libwebp0.6-0.6.0-1.el7.x86_64 conflicts with file from package libwebp-0.5.1-2.el7.x86_64"

**Comment by scaronni** [comment]
Please see the latest post:
https://negativo17.org/rhel-7-4-multimedia-packages-and-skype-repository-removal/

I will make a non-repo folder with the 4 required package updates required for RHEL 7.4 until CentOS 7.4 is released.

**Comment by scaronni** [comment]
Oh god, what a mess:

https://lists.fedoraproject.org/archives/list/epel-devel@lists.fedoraproject.org/message/XPEKJNQZ6EIIHRRMTB366UDON3VLGU3D/

**Comment by pgera** [comment]
Your post mentions, "to update the packages from the EPEL 7 multimedia repository you should run this command", but there's no command following that.

**Comment by scaronni** [comment]
meh, it was being mangled by the tags in wordpress. Updated to appear. Thanks for reporting.

**Comment by pgera** [comment]
Thanks. That worked on one system with a minimal install. The other one with a lot more packages still failes.

**Comment by scaronni** [comment]
Maybe I can help. Would you past the output?
You can use `yum --skip-broken update` until the RHEL 7.4 updates come up.

**Comment by pgera** [comment]
It's the same problem as before. Skip-broken gets stuck in a loop for a long time (that even ctrl c can't break; really annoying). The only reliable way right now is to remove the repo packages with nodeps, and do yum update. This is distro-sync's output:

```
Error: Package: gvfs-1.30.4-3.el7.x86_64 (rhel-x86_64-server-7)
           Requires: libbluray.so.1()(64bit)
           Available: libbluray-0.2.3-5.el7.x86_64 (rhel-x86_64-server-7)
               libbluray.so.1()(64bit)
           Installed: libbluray-1.0.1-1.el7.x86_64 (@epel-multimedia)
              ~libbluray.so.2()(64bit)
           Available: libbluray-1.0.0-1.el7.i686 (epel-multimedia)
               Not found
Error: Package: qt5-qtwebkit-5.6.1-3.b889f46git.el7.x86_64 (epel)
           Requires: qt5-qtbase(x86-64) = 5.6.1
           Removing: qt5-qtbase-5.6.1-10.el7.x86_64 (@rhel-7-server-rpms)
               qt5-qtbase(x86-64) = 5.6.1-10.el7
           Updated By: qt5-qtbase-5.6.2-1.el7.x86_64 (rhel-x86_64-server-7)
               qt5-qtbase(x86-64) = 5.6.2-1.el7
Error: Package: qt5-qtquickcontrols2-5.6.1-2.el7.x86_64 (@epel)
           Requires: qt5-qtgraphicaleffects(x86-64) = 5.6.1
           Removing: qt5-qtgraphicaleffects-5.6.1-10.el7.x86_64 (@rhel-x86_64-server-7)
               qt5-qtgraphicaleffects(x86-64) = 5.6.1-10.el7
           Updated By: qt5-qtgraphicaleffects-5.6.2-1.el7.x86_64 (rhel-x86_64-server-7)
               qt5-qtgraphicaleffects(x86-64) = 5.6.2-1.el7
Error: Package: qt5-qtquickcontrols2-5.6.1-2.el7.x86_64 (@epel)
           Requires: qt5-qtdeclarative(x86-64) = 5.6.1
           Removing: qt5-qtdeclarative-5.6.1-10.el7.x86_64 (@rhel-7-server-rpms)
               qt5-qtdeclarative(x86-64) = 5.6.1-10.el7
           Updated By: qt5-qtdeclarative-5.6.2-1.el7.x86_64 (rhel-x86_64-server-7)
               qt5-qtdeclarative(x86-64) = 5.6.2-1.el7
Error: Package: GraphicsMagick-1.3.26-3.el7.x86_64 (@epel-multimedia)
           Requires: libwebp.so.6()(64bit)
           Removing: libwebp-0.5.1-2.el7.x86_64 (@epel-multimedia)
               libwebp.so.6()(64bit)
           Downgraded By: libwebp-0.3.0-7.el7.x86_64 (rhel-x86_64-server-7)
              ~libwebp.so.4()(64bit)
Error: Package: kf5-kdeclarative-5.36.0-1.el7.x86_64 (epel)
           Requires: qt5-qtbase(x86-64) = 5.6.1
           Removing: qt5-qtbase-5.6.1-10.el7.x86_64 (@rhel-7-server-rpms)
               qt5-qtbase(x86-64) = 5.6.1-10.el7
           Updated By: qt5-qtbase-5.6.2-1.el7.x86_64 (rhel-x86_64-server-7)
               qt5-qtbase(x86-64) = 5.6.2-1.el7
Error: Package: qt5-qtquickcontrols2-5.6.1-2.el7.x86_64 (@epel)
           Requires: qt5-qtbase(x86-64) = 5.6.1
           Removing: qt5-qtbase-5.6.1-10.el7.x86_64 (@rhel-7-server-rpms)
               qt5-qtbase(x86-64) = 5.6.1-10.el7
           Updated By: qt5-qtbase-5.6.2-1.el7.x86_64 (rhel-x86_64-server-7)
               qt5-qtbase(x86-64) = 5.6.2-1.el7
Error: Package: qt5-qtwebkit-5.6.1-3.b889f46git.el7.x86_64 (epel)
           Requires: qt5-qtdeclarative(x86-64) = 5.6.1
           Removing: qt5-qtdeclarative-5.6.1-10.el7.x86_64 (@rhel-7-server-rpms)
               qt5-qtdeclarative(x86-64) = 5.6.1-10.el7
           Updated By: qt5-qtdeclarative-5.6.2-1.el7.x86_64 (rhel-x86_64-server-7)
               qt5-qtdeclarative(x86-64) = 5.6.2-1.el7
 You could try using --skip-broken to work around the problem
```

**Comment by scaronni** [comment]
So, for this:

```
Error: Package: GraphicsMagick-1.3.26-3.el7.x86_64 (@epel-multimedia)
```

Do a `rpm -e --nodeps GraphicsMagick && yum -y install GraphicsMagick`.

All of the qt5 stuff:

```
Error: Package: qt5-qtwebkit-5.6.1-3.b889f46git.el7.x86_64 (epel)
Error: Package: qt5-qtquickcontrols2-5.6.1-2.el7.x86_64 (@epel)
Error: Package: qt5-qtquickcontrols2-5.6.1-2.el7.x86_64 (@epel)
Error: Package: kf5-kdeclarative-5.36.0-1.el7.x86_64 (epel)
```

Are pending to go into testing updates:

https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2017-41c6892a24
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2017-3d57d65852

Click on "Builds" to download them, and if they work, please leave karma so they go faster into stable.

This one:

```
Error: Package: gvfs-1.30.4-3.el7.x86_64 (rhel-x86_64-server-7)
```

is one of the packages that need a rebuild, so please be patient. It pulls in a lot of new dependencies, so I would rather avoid picking them up one by one for adding them to the CentOS chroots.

**Comment by scaronni** [comment]
I've added a note to the blog post about this.

**Comment by pgera** [comment]
Tried the first one. Fails with:

```
Error: Package: GraphicsMagick-1.3.26-3.el7.x86_64 (epel)
           Requires: libwebp.so.4()(64bit)
           Available: libwebp-0.3.0-3.el7.x86_64 (rhel-x86_64-server-7)
               libwebp.so.4()(64bit)
           Available: libwebp-0.3.0-7.el7.x86_64 (rhel-x86_64-server-7)
               libwebp.so.4()(64bit)
           Installed: libwebp-0.5.1-2.el7.x86_64 (@epel-multimedia)
              ~libwebp.so.6()(64bit)
```

Edit: Removing libwebp with nodeps fixed this.

**Comment by scaronni** [comment]
Because of multipled failures, the distro-sync command did not work, so libwebp is still old:

```
rpm -e --nodeps GraphicsMagick libwebp && yum -y install GraphicsMagick
```
or, if you have fixed all other problems:
```
rpm -e --nodeps GraphicsMagick && yum distro-sync && yum -y install GraphicsMagick
```

**Comment by pgera** [comment]
I think libwebp0.6 needs to be installed manually after this, right ? Some other packages depend on that:

qt5-qtwebkit-5.6.1-5.b889f46git.el7.x86_64 has missing requires of libwebp.so.6()(64bit)
qtwebkit-2.3.4-8.el7.x86_64 has missing requires of libwebp.so.6()(64bit)
webkitgtk-2.4.9-3.el7.x86_64 has missing requires of libwebp.so.6()(64bit)
webkitgtk3-2.4.9-7.el7.x86_64 has missing requires of libwebp.so.6()(64bit)
zbar-0.10-27.el7.x86_64 has missing requires of libGraphicsMagick-Q16.so.3()(64bit)
zbar-0.10-27.el7.x86_64 has missing requires of libGraphicsMagickWand-Q16.so.2()(64bit)

**Comment by scaronni** [comment]
Nope, those will be reinstalled are part of distro-sync. They will get to the RHEL 7.4 versions which use libwebp.so.4()(64bit). Paste your output again.

You have not reinstalled GraphicsMagick, btw.

**Comment by scaronni** [comment]
I've updated the post again. I've posted a temporary repository containing 7.4 packages until CentOS 7.4 is released.
